# Generated by Django 2.2.4 on 2019-08-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='params',
            field=models.TextField(null=True, verbose_name='Params'),
        ),
    ]
