# Generated by Django 2.2.4 on 2019-08-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='path',
            field=models.URLField(blank=True, default='', max_length=256, verbose_name='Path'),
            preserve_default=False,
        ),
    ]
