# Generated by Django 2.2.4 on 2019-08-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190807_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Path'),
        ),
    ]
