# Generated by Django 2.2.4 on 2019-08-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20190807_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='uid',
            field=models.CharField(choices=[('report1', 'report1'), ('report2', 'report2')], default='report1', max_length=64, verbose_name='Unique ID'),
        ),
    ]
