# Generated by Django 2.2.4 on 2019-08-08 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0006_auto_20190807_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.CharField(max_length=32, verbose_name='File')),
                ('path', models.CharField(blank=True, help_text='For S3, this starts with your bucket', max_length=256, null=True, verbose_name='Path')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Report')),
            ],
            options={
                'verbose_name_plural': 'Deliveries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Name')),
                ('kind', models.CharField(choices=[('s3', 'S3'), ('ftp', 'FTP'), ('sftp', 'SFTP'), ('email', 'Email')], db_index=True, default='s3', max_length=32, verbose_name='Kind')),
                ('host', models.CharField(blank=True, help_text='FTP or SFTP host', max_length=128, null=True, verbose_name='Host')),
                ('username', models.CharField(blank=True, help_text='For S3, this is your access key', max_length=128, null=True, verbose_name='Username')),
                ('_password', models.CharField(blank=True, db_column='password', help_text='For S3, this is your secret', max_length=256, null=True, verbose_name='Password')),
                ('path', models.CharField(blank=True, help_text='For S3, this starts with your bucket', max_length=256, null=True, verbose_name='Path')),
                ('emails', models.CharField(blank=True, help_text='Comma-delimited list of email addresses', max_length=128, null=True, verbose_name='Emails')),
                ('include_attachment', models.BooleanField(default=False, verbose_name='Include attachment')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
            ],
            options={
                'verbose_name_plural': 'Targets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('stopped', 'stopped'), ('failed', 'failed'), ('completed', 'completed')], db_index=True, default='pending', max_length=16, verbose_name='Status')),
                ('url', models.URLField(blank=True, max_length=256, null=True, verbose_name='URL')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='msg')),
                ('task_id', models.CharField(max_length=128, null=True, verbose_name='task_id')),
                ('delivery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.Delivery')),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.History')),
            ],
            options={
                'verbose_name_plural': 'History',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='delivery',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.Target'),
        ),
    ]
