# Generated by Django 2.2.4 on 2019-08-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='file',
        ),
    ]
