# Generated by Django 2.2.4 on 2019-08-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_remove_delivery_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='_password',
        ),
    ]
